"""Pipeline state definitions — the data contract between all Agents."""

from __future__ import annotations

from typing import Optional, TypedDict

from pydantic import BaseModel, Field


# ── Pydantic models (validated data objects) ─────────────────────────


class UserBrief(BaseModel):
    """User input that kicks off a pipeline run."""

    topic: str = Field(description="Main topic or theme")
    keywords: list[str] = Field(default_factory=list, description="Search keywords")
    platform_hints: list[str] = Field(default_factory=list, description="Target platforms")
    style: str = Field(default="", description="Content style hint")
    extra: dict = Field(default_factory=dict, description="Arbitrary extra params")


class Topic(BaseModel):
    """A candidate topic generated by the topic agent."""

    title: str
    angle: str = Field(default="", description="The angle or hook")
    score: float = Field(default=0.0, description="Relevance/quality score 0-10")
    reasoning: str = Field(default="", description="Why this topic was chosen")


class Material(BaseModel):
    """A piece of reference material collected by the material agent."""

    source: str = Field(description="URL or file path")
    title: str = Field(default="")
    snippet: str = Field(default="", description="Relevant excerpt")
    source_type: str = Field(default="web", description="web | local_kb | manual")


class PlatformContent(BaseModel):
    """Generated content for a specific platform."""

    platform: str
    title: str
    body: str
    tags: list[str] = Field(default_factory=list)
    image_paths: list[str] = Field(default_factory=list)
    image_prompts: list[str] = Field(default_factory=list, description="Prompts used for image gen")


class ReviewResult(BaseModel):
    """Review outcome for a piece of content."""

    platform: str
    passed: bool
    score: float = Field(default=0.0, description="Quality score 0-10")
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


class Analysis(BaseModel):
    """Post-publish analytics and insights."""

    summary: str = Field(default="")
    insights: list[str] = Field(default_factory=list)
    improvement_suggestions: list[str] = Field(default_factory=list)


class PipelineError(BaseModel):
    """An error that occurred during pipeline execution."""

    agent: str
    error_type: str
    message: str
    recoverable: bool = Field(default=True)


class StageConfig(BaseModel):
    """One stage in a pipeline YAML."""

    agent: str
    config: dict = Field(default_factory=dict)
    on_error: str = Field(default="halt", description="skip | retry | halt")
    retry_count: int = Field(default=1)


class PipelineConfig(BaseModel):
    """Loaded from YAML — describes a pipeline."""

    name: str
    description: str = ""
    platforms: list[str] = Field(default_factory=list)
    stages: list[StageConfig] = Field(default_factory=list)


# ── LangGraph State (TypedDict — not Pydantic) ──────────────────────


class PipelineState(TypedDict, total=False):
    """The shared state flowing through the LangGraph pipeline.

    Each key = one Agent's output = another Agent's input.
    Using total=False so agents only need to return the fields they produce.
    """

    # Run identity
    run_id: str
    pipeline_name: str
    user_brief: dict  # serialized UserBrief

    # Topic stage
    topics: list[dict]  # serialized list[Topic]
    selected_topic: dict  # serialized Topic

    # Material stage
    materials: list[dict]  # serialized list[Material]

    # Generation stage (keyed by platform name)
    contents: dict[str, dict]  # {platform: serialized PlatformContent}

    # Review stage
    reviews: dict[str, dict]  # {platform: serialized ReviewResult}

    # Analytics stage
    analysis: dict  # serialized Analysis

    # Flow control
    stage: str
    errors: list[dict]  # serialized list[PipelineError]
    metadata: dict
