"""Pipeline state definitions — the data contract between all Agents."""

from __future__ import annotations

from typing import Optional, TypedDict

from pydantic import BaseModel, Field


# ── Pydantic models (validated data objects) ─────────────────────────


class SourceDocument(BaseModel):
    """A source document provided by the user as input."""

    file_path: str = Field(description="Absolute path to the document file")
    title: str = Field(default="", description="Document title or filename")
    content: str = Field(default="", description="Full text content")
    extracted_images: list["ExtractedImage"] = Field(default_factory=list)


class ExtractedImage(BaseModel):
    """An image extracted from a source document."""

    image_path: str = Field(description="Local file path to the image")
    source_doc_path: str = Field(description="Which document this image came from")
    caption: str = Field(default="", description="Vision-generated caption")
    page_anchor: str = Field(default="", description="Page/slide/position hint")


class InlineImageSpec(BaseModel):
    """Specification for an image to be generated via skill during post-processing."""

    skill_name: str = Field(description="Which skill to invoke: architecture-diagram | obsidian-canvas | excalidraw-diagram | minimax-image")
    prompt: str = Field(description="The prompt/definition for the skill")
    caption: str = Field(default="", description="Caption for the image")
    context: str = Field(default="", description="Where in the article this image appears")
    output_path: str = Field(default="", description="Set by post_processor after generation")


class ImageSource(BaseModel):
    """Tracks the source of an image used in content."""

    image_path: str = Field(description="Path to the image")
    source_type: str = Field(description="real_document | extracted | skill_screenshot | ai_generated")
    source_detail: str = Field(default="", description="e.g. skill name, document path, or prompt used")


class UserBrief(BaseModel):
    """User input that kicks off a pipeline run."""

    topic: str = Field(description="Main topic or theme")
    keywords: list[str] = Field(default_factory=list, description="Search keywords")
    platform_hints: list[str] = Field(default_factory=list, description="Target platforms")
    style: str = Field(default="", description="Content style hint")
    extra: dict = Field(default_factory=dict, description="Arbitrary extra params")
    source_documents: list[SourceDocument] = Field(default_factory=list, description="User-provided source documents")


class Topic(BaseModel):
    """A candidate topic generated by the topic agent."""

    title: str
    angle: str = Field(default="", description="The angle or hook")
    score: float = Field(default=0.0, description="Relevance/quality score 0-10")
    reasoning: str = Field(default="", description="Why this topic was chosen")


class Material(BaseModel):
    """A piece of reference material collected by the material agent."""

    source: str = Field(description="URL or file path")
    title: str = Field(default="")
    snippet: str = Field(default="", description="Relevant excerpt")
    source_type: str = Field(default="web", description="web | local_kb | manual | document")
    source_url: Optional[str] = Field(default=None, description="Canonical URL for web materials; required for web type, may be null for document type")


class PlatformContent(BaseModel):
    """Generated content for a specific platform."""

    platform: str
    title: str
    body: str
    tags: list[str] = Field(default_factory=list)
    image_paths: list[str] = Field(default_factory=list)
    image_prompts: list[str] = Field(default_factory=list, description="Prompts used for image gen")
    image_sources: list[dict] = Field(default_factory=list, description="ImageSource dicts tracking each image's origin")
    inline_images: list[dict] = Field(default_factory=list, description="InlineImageSpec specs for post-processor to generate")


class ReviewFailure(BaseModel):
    """A single review failure with rule, current value, and expected value."""

    rule: str = Field(description="Rule identifier (e.g. body_min_length, has_emoji)")
    message: str = Field(default="", description="Human-readable failure message")
    current: str = Field(default="", description="Current value that failed")
    expected: str = Field(default="", description="Expected value")


class ReviewResult(BaseModel):
    """Review outcome for a piece of content."""

    platform: str
    passed: bool
    score: float = Field(default=0.0, description="Quality score 0-10")
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    failures: list[ReviewFailure] = Field(default_factory=list, description="Structured failures for auto-retry")
    retryable: bool = Field(default=False, description="Whether this failure can be retried automatically")
    retry_hint: str = Field(default="", description="Hint for content_generator on how to fix failures")


class Analysis(BaseModel):
    """Post-publish analytics and insights."""

    summary: str = Field(default="")
    insights: list[str] = Field(default_factory=list)
    improvement_suggestions: list[str] = Field(default_factory=list)


class PipelineError(BaseModel):
    """An error that occurred during pipeline execution."""

    agent: str
    error_type: str
    message: str
    recoverable: bool = Field(default=True)


class StageConfig(BaseModel):
    """One stage in a pipeline YAML."""

    agent: str
    config: dict = Field(default_factory=dict)
    on_error: str = Field(default="halt", description="skip | retry | halt")
    retry_count: int = Field(default=1)
    model_override: str | None = Field(default=None, description="Override model name for this stage")
    model_provider: str | None = Field(default=None, description="Override model provider for this stage")
    prompt_override: str | None = Field(default=None, description="Override prompt template with raw text")


class PipelineConfig(BaseModel):
    """Loaded from YAML — describes a pipeline."""

    name: str
    description: str = ""
    platforms: list[str] = Field(default_factory=list)
    stages: list[StageConfig] = Field(default_factory=list)


# ── LangGraph State (TypedDict — not Pydantic) ──────────────────────


class PipelineState(TypedDict, total=False):
    """The shared state flowing through the LangGraph pipeline.

    Each key = one Agent's output = another Agent's input.
    Using total=False so agents only need to return the fields they produce.
    """

    # Run identity
    run_id: str
    pipeline_name: str
    user_brief: dict  # serialized UserBrief

    # Topic stage
    topics: list[dict]  # serialized list[Topic]
    selected_topic: dict  # serialized Topic

    # Document processing stages
    source_documents: list[dict]  # serialized list[SourceDocument]
    document_synthesizer_output: dict  # serialized DocumentSynthesizerOutput
    extracted_images: list[dict]  # serialized list[ExtractedImage]

    # Material stage
    materials: list[dict]  # serialized list[Material]

    # Generation stage (keyed by platform name)
    contents: dict[str, dict]  # {platform: serialized PlatformContent}

    # Review loop state
    review_iteration: int          # current iteration count (0 = initial)
    previous_review_issues: list[str]  # issues from previous review pass (for content_generator correction)

    # Post-processing stage
    inline_images: list[dict]  # serialized list[InlineImageSpec]

    # Review stage
    reviews: dict[str, dict]  # {platform: serialized ReviewResult}

    # Analytics stage
    analysis: dict  # serialized Analysis

    # Flow control
    stage: str
    errors: list[dict]  # serialized list[PipelineError]
    metadata: dict
