"""Database model constants and helpers."""

STATUS_PENDING_REVIEW = "pending_review"
STATUS_APPROVED = "approved"
STATUS_REJECTED = "rejected"
STATUS_PUBLISHED = "published"

RUN_STATUS_PENDING = "pending"
RUN_STATUS_RUNNING = "running"
RUN_STATUS_COMPLETED = "completed"
RUN_STATUS_FAILED = "failed"

ALL_CONTENT_STATUSES = [STATUS_PENDING_REVIEW, STATUS_APPROVED, STATUS_REJECTED, STATUS_PUBLISHED]
ALL_RUN_STATUSES = [RUN_STATUS_PENDING, RUN_STATUS_RUNNING, RUN_STATUS_COMPLETED, RUN_STATUS_FAILED]
